# IDEAW model configuration

IDEAW:
  ## for STFT and ISTFT
  n_fft: 1000
  hop_len: 250
  win_len: 1000
  ## for expanding watermark message
  num_bit: 16
  num_point: 16000

## for invertible block
InnBlock:
  channel: 2
  clamp: 2

Mihnet:

Discriminator:

Restorer: