# IDEAW model configuration

IDEAW:
  num_inn: 1
  ## for STFT and ISTFT
  n_fft: 1000
  hop_len: 250
  win_len: 1000
  ## for expanding watermark message
  num_bit: 16
  num_lc_bit: 10
  num_point: 16000

## for invertible block
InnBlock:
  channel: 2
  clamp: 2

Discriminator:
  input_size: 16000

Restorer:

AttackLayer:
  GaussianNoise:
    snr: 10
  Bandpass:
    upper: 5000
    lower: 1000
  Dropout:
    p: 0.05
  Resample:
    sr: 14400
  AmplitudeModify:
    f: 0.90
  Compress:
    threshold: -20.0
    cr: 2
  TimeStretch:
    rate: 0.90